version: '3.8'

services:
  ml-api:
    build: .
    ports:
      - "8001:8000"
    environment:
      - PETS_DATABASE_PATH=${PETS_DATABASE_PATH}
      - API_URL=${API_URL}
      - BOT_TOKEN=${BOT_TOKEN}
      - ACCESS_TOKEN=${ACCESS_TOKEN}
      - SB_AUTH_DATA=${SB_AUTH_DATA}
      - CACHE_TTL=${CACHE_TTL}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - ml-api-network

networks:
  ml-api-network:
    driver: bridge
