version: '3.8'

services:
  ml-api:
    build: .
    ports:
      - "8001:8000"
    environment:
      - PETS_DATABASE_PATH=${PETS_DATABASE_PATH}
      - API_URL=${API_URL}
      - BOT_TOKEN=${BOT_TOKEN}
      - ACCESS_TOKEN=${ACCESS_TOKEN}
      - SB_AUTH_DATA=${SB_AUTH_DATA}
      - CACHE_TTL=${CACHE_TTL}
    volumes:
      - .:/app
    command: ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    networks:
      - ml-api-network

networks:
  ml-api-network:
    driver: bridge
